# Generated by Django 4.0.3 on 2022-06-25 22:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative')], default='', max_length=5)),
                ('biography', models.CharField(default='', max_length=1000)),
                ('year_formed', models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)])),
                ('active', models.BooleanField(default=True)),
                ('official_homepage', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mol_rechercher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('nom', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='releve_Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('nom', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='summary_pdf',
            fields=[
                ('titre', models.CharField(default='', max_length=100)),
                ('file', models.FileField(upload_to='ville/pdf/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ville', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('year_created', models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)])),
                ('band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affichage.band')),
            ],
        ),
    ]
