# Generated by Django 4.0.3 on 2022-03-22 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affichage', '0004_titre_year_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='titre',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affichage.band'),
        ),
    ]
