# Generated by Django 4.0.3 on 2022-04-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affichage', '0005_titre_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='releve_Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
    ]
