# Generated by Django 4.0.3 on 2022-04-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affichage', '0006_releve_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='releve_ville',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
