# Generated by Django 4.0.3 on 2022-04-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affichage', '0007_releve_ville_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='summary_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='', max_length=100)),
                ('file', models.FileField(upload_to='ville/pdf/')),
            ],
        ),
    ]
