# Generated by Django 4.0.3 on 2022-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affichage', '0008_summary_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary_pdf',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
