# Generated by Django 4.0.3 on 2022-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affichage', '0010_summary_pdf_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='mol_rechercher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('nom', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
